# Generated by Django 5.1.1 on 2024-10-02 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shield', models.ImageField(upload_to='shields/')),
                ('team', models.ImageField(upload_to='teams/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='players/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_players', to='album.team')),
            ],
        ),
    ]
